def fromUSPS( s ):
   ''' Given a two-character US Postal Service abbreviation,returns the corresponding state. Includes territories. '''
   s = s.upper()
   usps = {
      'AK': 'Alaska',
      'AL': 'Alabama',
      'AR': 'Arkansas',
      'AS': 'American Samoa',
      'AZ': 'Arizona',
      'CA': 'California',
      'CO': 'Colorado',
      'CT': 'Connecticut',
      'DC': 'District of Columbia',
      'DE': 'Delaware',
      'FL': 'Florida',
      'GA': 'Georgia',
      'GU': 'Guam',
      'HI': 'Hawaii',
      'IA': 'Iowa',
      'ID': 'Idaho',
      'IL': 'Illinois',
      'IN': 'Indiana',
      'KS': 'Kansas',
      'KY': 'Kentucky',
      'LA': 'Louisiana',
      'MA': 'Massachusetts',
      'MD': 'Maryland',
      'ME': 'Maine',
      'MI': 'Michigan',
      'MN': 'Minnesota',
      'MO': 'Missouri',
      'MP': 'Northern Mariana Islands',
      'MS': 'Mississippi',
      'MT': 'Montana',
      'NA': 'National',
      'NC': 'North Carolina',
      'ND': 'North Dakota',
      'NE': 'Nebraska',
      'NH': 'New Hampshire',
      'NJ': 'New Jersey',
      'NM': 'New Mexico',
      'NV': 'Nevada',
      'NY': 'New York',
      'OH': 'Ohio',
      'OK': 'Oklahoma',
      'OR': 'Oregon',
      'PA': 'Pennsylvania',
      'PR': 'Puerto Rico',
      'RI': 'Rhode Island',
      'SC': 'South Carolina',
      'SD': 'South Dakota',
      'TN': 'Tennessee',
      'TX': 'Texas',
      'UT': 'Utah',
      'VA': 'Virginia',
      'VI': 'Virgin Islands',
      'VT': 'Vermont',
      'WA': 'Washington',
      'WI': 'Wisconsin',
      'WV': 'West Virginia',
      'WY': 'Wyoming'
      }
   return usps[s]

def toUSPS(s):
   ''' Given a state or territory name, returns the two character US Postal Service abbreviation. '''
   s = s.upper()
   states = {
      'ALASKA':'AK',
      'ALABAMA':'AL',
      'ARKANSAS':'AR',
      'AMERICAN SAMOA':'AS',
      'ARIZONA':'AZ',
      'CALIFORNIA':'CA',
      'COLORADO':'CO',
      'CONNECTICUT':'CT',
      'DISTRICT OF COLUMBIA':'DC',
      'DELAWARE':'DE',
      'FLORIDA':'FL',
      'GEORGIA':'GA',
      'GUAM':'GU',
      'HAWAII':'HI',
      'HAWAI\'I':'HI',
      'IOWA':'IA',
      'IDAHO':'ID',
      'ILLINOIS':'IL',
      'INDIANA':'IN',
      'KANSAS':'KS',
      'KENTUCKY':'KY',
      'LOUISIANA':'LA',
      'MASSACHUSETTS':'MA',
      'MARYLAND':'MD',
      'MAINE':'ME',
      'MICHIGAN':'MI',
      'MINNESOTA':'MN',
      'MISSOURI':'MO',
      'NORTHERN MARIANA ISLANDS':'MP',
      'MISSISSIPPI':'MS',
      'MONTANA':'MT',
      'NATIONAL':'NA',
      'NORTH CAROLINA':'NC',
      'NORTH DAKOTA':'ND',
      'NEBRASKA':'NE',
      'NEW HAMPSHIRE':'NH',
      'NEW JERSEY':'NJ',
      'NEW MEXICO':'NM',
      'NEVADA':'NV',
      'NEW YORK':'NY',
      'OHIO':'OH',
      'OKLAHOMA':'OK',
      'OREGON':'OR',
      'PENNSYLVANIA':'PA',
      'PUERTO RICO':'PR',
      'RHODE ISLAND':'RI',
      'SOUTH CAROLINA':'SC',
      'SOUTH DAKOTA':'SD',
      'TENNESSEE':'TN',
      'TEXAS':'TX',
      'UTAH':'UT',
      'VIRGINIA':'VA',
      'VIRGIN ISLANDS':'VI',
      'VERMONT':'VT',
      'WASHINGTON':'WA',
      'WISCONSIN':'WI',
      'WEST VIRGINIA':'WV',
      'WYOMING':'WY'
      }
   return states[s]

